require("uelei.options")
require("uelei.plugin.treesitter")
require("uelei.keymaps")
require("uelei.plugin.git")
require("uelei.plugin.org")
require("uelei.lsp")
require("uelei.cmp")
require("uelei.null-ls")
require("uelei.plugin.telescope")
-- require("uelei.plugin.lualine")
